Fix AttributeError NoneType has no attribute 'style'  (#283)
* fix AttributeError NoneType has no attribute 'style' when using INCAR tag 'kspacing' instead of KPOINTS file

* fix KeyError custodian/vasp/tests/test_handlers.py:229:          #

The next correction check ISYM and no CHGCAR
        h.correct()
        vi = VaspInput.from_directory(".")
>       assert vi["INCAR"]["ISYM"] == 0
E       KeyError: 'ISYM'

* simplify 'if vi["KPOINTS"] is not None' to 'if vi["KPOINTS"]'

* pytest GH action only run on PR/psuh to master and ignore docs changes