pre-commit autoupdate (#332)
* pre-commit autoupdate

updates:
- [github.com/astral-sh/ruff-pre-commit: v0.3.5 → v0.4.3](https://github.com/astral-sh/ruff-pre-commit/compare/v0.3.5...v0.4.3)
- [github.com/pre-commit/pre-commit-hooks: v4.5.0 → v4.6.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.5.0...v4.6.0)
- [github.com/pre-commit/mirrors-mypy: v1.9.0 → v1.10.0](https://github.com/pre-commit/mirrors-mypy/compare/v1.9.0...v1.10.0)

* ruff auto fixes

* manual ruff fixes

* fix typos and doc strings

* fix AttributeError: 'list' object has no attribute 'astype'

if self.half_kpts and os.path.isfile(os.path.join(directory, "KPOINTS")):
            kpts = Kpoints.from_file(os.path.join(directory, "KPOINTS"))
            kpts.kpts = np.maximum(np.array(kpts.kpts) / 2, 1)
>           kpts.kpts = kpts.kpts.astype(int).tolist()

* fix more directory kwargs missing in doc strings

---------

Co-authored-by: Janosh Riebesell <janosh.riebesell@gmail.com>